FROM rust:1.93

RUN apt-get update && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*
RUN cargo install diesel_cli --no-default-features --features postgres --version 2.2.6

WORKDIR /app

COPY ./diesel.toml ./
COPY ./migrations/ /migrations

CMD ["diesel", "migration", "run", "--migration-dir", "/migrations"]
