FROM rust:1.93

RUN cargo install sqlx-cli --no-default-features --features rustls,postgres --version 0.8.2

WORKDIR /app

COPY ./api/migrations/ /migrations

CMD ["sqlx", "migrate", "run", "--source", "/migrations"]
